# Generated by Django 3.2.4 on 2021-09-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=164)),
                ('slug', models.SlugField(default=models.CharField(max_length=164), max_length=140)),
                ('summary', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_on', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('complete', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
            },
        ),
    ]
